# 50 Numpy Functions!!!

### Installation

##### Run the code below to install NumPy:

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


##### Run the code below to import NumPy:

In [2]:
import numpy

Run the code below to import StringIO:

In [3]:
from io import StringIO

Now that you have finished installing NumPy, we can now move onto writing NumPy Functions.

### NumPy Functions

##### Function 1: "numpy.ndarray()"

This Function is used to create an NDArray of the dimensions specified (in this case, it's 2 x 2). Random values are generated for the NDArray.

In [4]:
myArray = numpy.ndarray((5, 5))
print(myArray)

[[4.64705064e-310 0.00000000e+000 6.91501177e-310 6.91501177e-310
  6.91501177e-310]
 [6.91501177e-310 6.91501177e-310 6.91501177e-310 6.91501177e-310
  6.91501177e-310]
 [6.91501177e-310 6.91501177e-310 6.91501177e-310 6.91501177e-310
  6.91501177e-310]
 [6.91501177e-310 6.91501177e-310 6.91501177e-310 6.91501177e-310
  6.91501177e-310]
 [6.91501177e-310 6.91501177e-310 6.91501177e-310 6.91501177e-310
  1.02765654e-321]]


##### Function 2: "numpy.array()"

This Function is used to create an NDArray from the List/Tuple specified (in this case, a Tuple with the values 4, 8, 2, 6 and 5). NumPy is responsible for converting this List/Tuple into an NDArray.

In [5]:
numpy.array((4, 8, 2, 6, 5))

array([4, 8, 2, 6, 5])

##### Function 3: "numpy.arange()"

This Function is used to create an NDArray from the Range of Values specified (in this case, the NDArray will start from 3 and end at 25, while taking 2 steps).

In [6]:
numpy.arange(3, 25, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

##### Function 4: "numpy.abs()"

This Function is used to convert all the Elements of an NDArray to their Absolute Value (so if an Element is -25, it will be converted to 25).

In [7]:
array = numpy.array([5, 9, -2, -5, 14, 18, -25, -53])
print(array)

[  5   9  -2  -5  14  18 -25 -53]


In [8]:
newArray = numpy.abs(array)
print(newArray)

[ 5  9  2  5 14 18 25 53]


##### Function 5: "numpy.sqrt()"

This Function is used to convert all the Elements of an NDArray to their Square Root (so if an Element is 9, it will be converted to 3).

In [9]:
numpy.sqrt(newArray)

array([2.23606798, 3.        , 1.41421356, 2.23606798, 3.74165739,
       4.24264069, 5.        , 7.28010989])

##### Function 6: "numpy.square()"

This Function is used to convert all the Elements of an NDArray to their Square (so if an Element is 3, it will be converted to 9).

In [10]:
newArray = numpy.square(newArray)
print(newArray)

[  25   81    4   25  196  324  625 2809]


##### Function 7: "numpy.ceil()"

This Function is used to Return the Ceiling of all the Decimal Elements in an NDArray, Element-Wise (so if an Element is 2.3, it will Round to 3.0 or if an Element is -2.3, it will Round to -2.0).

In [11]:
decimalArray = numpy.array([2.3, 3.0, 6.4, -12.87, 13.63, 14.42, 91.82, -19.36])
print(decimalArray)

[  2.3    3.     6.4  -12.87  13.63  14.42  91.82 -19.36]


In [12]:
ceiledDecimalArray = numpy.ceil(decimalArray)
print(ceiledDecimalArray)

[  3.   3.   7. -12.  14.  15.  92. -19.]


##### Function 8: "numpy.floor()"

This Function is used to Return the Floor of all the Decimal Elements in an NDArray, Element Wise (so if an Element is 2.3, it will Round to 2.0 or if an Element is -2.3, it will Round to -3.0).

In [13]:
flooredDecimalArray = numpy.floor(decimalArray)
print(flooredDecimalArray)

[  2.   3.   6. -13.  13.  14.  91. -20.]


##### Function 9: "numpy.modf()"

This Function is used to Return the Fractional and Integral parts of an NDArray, Element Wise (so if an Element is 2.3, 0.3 will go into the Fractional Array and 2.0 will go into the Integral Array).

In [14]:
numpy.modf(decimalArray)

(array([ 0.3 ,  0.  ,  0.4 , -0.87,  0.63,  0.42,  0.82, -0.36]),
 array([  2.,   3.,   6., -12.,  13.,  14.,  91., -19.]))

##### Function 10: "numpy.add()"

This Function is used to Add the Elements of 2 NDArrays together.

In [15]:
numpy.add(array, newArray)

array([  30,   90,    2,   20,  210,  342,  600, 2756])

##### Function 11: "numpy.subtract()"

This Function is used to Subtract the Elements of 2 NDArrays together.

In [16]:
numpy.subtract(array, newArray)

array([  -20,   -72,    -6,   -30,  -182,  -306,  -650, -2862])

##### Function 12: "numpy.multiply()"

This Function is used to Multiply the Elements of 2 NDArrays together.

In [17]:
numpy.multiply(array, newArray)

array([    125,     729,      -8,    -125,    2744,    5832,  -15625,
       -148877])

##### Function 13: "numpy.divide()"

This Function is used to Divide the Elements of 2 NDArrays together.

In [18]:
numpy.divide(array, newArray)

array([ 0.2       ,  0.11111111, -0.5       , -0.2       ,  0.07142857,
        0.05555556, -0.04      , -0.01886792])

##### Function 14: "numpy.floor_divide()"

This Function is used to Floor Divide the Elements of 2 NDArrays together (this means that if i'm dividing 7 and 3, instead of outputting 2.33, it will output 2 for example).

In [19]:
numpy.floor_divide(7, 3)

2

##### Function 15: "numpy.power()"

This Function is used to calculate the Power of the Elements of 2 NDArrays together (this means that if i'm powering 7 and 3, it will output 343).

In [20]:
numpy.power(7, 3)

343

##### Function 16: "numpy.maximum()"

This Function is used to calculate the Largest Number for each Element in the 2 NDArrays you are comparing.

In [21]:
numpy.maximum(array, newArray)

array([  25,   81,    4,   25,  196,  324,  625, 2809])

##### Function 17: "numpy.minimum()"

This Function is used to calculate the Smallest Number for each Element in the 2 NDArrays you are comparing.

In [22]:
numpy.minimum(array, newArray)

array([  5,   9,  -2,  -5,  14,  18, -25, -53])

##### Function 18: "numpy.mod/remainder()"

This Function is used to calculate the Remainder when you divide 2 Elements together (it acts just like the Modulo Operator in Default Python). You can use "numpy.mod()" or "numpy.remainder()" as they are each Aliases of each other.

In [23]:
numpy.mod(7, 3)

1

In [24]:
numpy.remainder(7, 3)

1

##### Function 19: "numpy.divmod()"

This Function does the same thing as "numpy.modf()" and "numpy.mod/remainder()" at the same time!

In [25]:
numpy.divmod(decimalArray, newArray)

(array([ 0.,  0.,  1., -1.,  0.,  0.,  0., -1.]),
 array([2.30000e+00, 3.00000e+00, 2.40000e+00, 1.21300e+01, 1.36300e+01,
        1.44200e+01, 9.18200e+01, 2.78964e+03]))

##### Function 20: "numpy.greater()"

This Function calculates which number is Greater than the other when comparing Elements in 2 NDArrays.

In [26]:
numpy.greater(array, decimalArray)

array([ True,  True, False,  True,  True,  True, False, False])

##### Function 21: "numpy.greater_equal()"

This Function calculates which number is Greater than or Equal to the other when comparing Elements in 2 NDArrays.

In [27]:
numpy.greater_equal(array, decimalArray)

array([ True,  True, False,  True,  True,  True, False, False])

##### Function 22: "numpy.less()"

This Function calculates which number is Less than the other when comparing Elements in 2 NDArrays.

In [28]:
numpy.less(array, decimalArray)

array([False, False,  True, False, False, False,  True,  True])

##### Function 23: "numpy.less_equal()"

This Function calculates which number is Less than or Equal to the other when comparing Elements in 2 NDArrays.

In [29]:
numpy.less_equal(array, decimalArray)

array([False, False,  True, False, False, False,  True,  True])

##### Function 24: "numpy.equal()"

This Function calculates which number ie Equal to the other when comparing Elements in 2 NDArrays.

In [30]:
numpy.equal(array, decimalArray)

array([False, False, False, False, False, False, False, False])

##### Function 25: "numpy.not_equal()"

This Function calculates which number is Not Equal to the other when comparing Elements in 2 NDArrays.

In [31]:
numpy.not_equal(array, decimalArray)

array([ True,  True,  True,  True,  True,  True,  True,  True])

##### Function 26: "\*NDArray Name\*.reshape()"

This Function reshapes the NDArray specified to a compatible Dimension specified without changing the Elements/Values.

In [32]:
array2 = numpy.arange(6).reshape(3, 2)
print(array2)

[[0 1]
 [2 3]
 [4 5]]


##### Function 27: "numpy.sum()"

This Function calculates the Sum of the Elements of the NDArray given.

In [33]:
numpy.sum(array)

-39

##### Function 28: "numpy.mean()"

This Function calculates the Mean (Average) of the NDArray Elements given.

In [34]:
numpy.mean(decimalArray)

12.417499999999999

##### Function 29: "numpy.amax()"

This Function returns the biggest Element in the NDArray provided.

In [35]:
numpy.amax(decimalArray)

91.82

##### Function 30: "numpy.amin()"

This Function returns the smallest Element in the NDArray provided.

In [36]:
numpy.amin(decimalArray)

-19.36

##### Function 31: "numpy.unique()"

This Function returns the Non-Repeated Elements in an NDArray.

In [37]:
repeatedArray = numpy.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 8, 9, 256])
print(numpy.unique(repeatedArray))

[  1   2   3   4   5   6   8   9 256]


##### Function 32: "numpy.repeat()"

This Function repeats the Elements of an NDArray according to the number of Repititions specified (so for example, it can repeat the number 3 in an NDArray 5 times).

In [38]:
numpy.repeat(3, 5)

array([3, 3, 3, 3, 3])

##### Function 33: "numpy.random.randint()"

This Function generates a Random Number based on the Parameters given (the first one defines from which number the Generation should start (Low) and the second number defines from which number the Generation should stop (High) (if the High number is not defined, then the Generation will start from 0 and stop at the Low number)).

In [39]:
numpy.random.randint(1, 7)

4

##### Function 34: "numpy.random.choice()"

This Function returns a Random Number from the given NDArray.

In [40]:
numpy.random.choice([1, 6, 2, 5, 4, 6, 7, 8, 24])

6

##### Function 35: "numpy.squeeze()"

This Function removes Single-Dimensional Entries from an NDArray (if the Axis selected is greater than 1 a ValueError is raised).

In [41]:
numpy.squeeze([[[5], [3]]], axis=2)

array([[5, 3]])

##### Function 36: "numpy.linspace()"

This Function is similar to "numpy.arange()" but instead of a Step Value, you provide the number of outputs (Endpoint) to be Generated (so if I start at 3 and stop at 25 and specify the endpoint to be 50, NumPy has to generate 50 values between 3 and 25).

In [42]:
numpy.linspace(3, 25, 50)

array([ 3.        ,  3.44897959,  3.89795918,  4.34693878,  4.79591837,
        5.24489796,  5.69387755,  6.14285714,  6.59183673,  7.04081633,
        7.48979592,  7.93877551,  8.3877551 ,  8.83673469,  9.28571429,
        9.73469388, 10.18367347, 10.63265306, 11.08163265, 11.53061224,
       11.97959184, 12.42857143, 12.87755102, 13.32653061, 13.7755102 ,
       14.2244898 , 14.67346939, 15.12244898, 15.57142857, 16.02040816,
       16.46938776, 16.91836735, 17.36734694, 17.81632653, 18.26530612,
       18.71428571, 19.16326531, 19.6122449 , 20.06122449, 20.51020408,
       20.95918367, 21.40816327, 21.85714286, 22.30612245, 22.75510204,
       23.20408163, 23.65306122, 24.10204082, 24.55102041, 25.        ])

##### Function 37: "numpy.full()"

This Function creates an NDArray of the Dimensions and Values specified (so I can create an NDArray with the Dimensions 2 x 3 with all the values being 8).

In [43]:
numpy.full((2, 3), 8)

array([[8, 8, 8],
       [8, 8, 8]])

##### Function 38: "\*NDArray\*.size"

This Function outputs the Size (Number 
Of Elements) of the NDArray specified.

In [44]:
myArray.size

25

##### Function 39: "\*NDArray\*.shape"

This Function outputs the Shape (Dimensions) of the NDArray specified.

In [45]:
myArray.shape

(5, 5)

##### Function 40: "\*NDArray*\.dtype"

This Function outputs the Data Type of the NDArray specified.

In [46]:
myArray.dtype

dtype('float64')

##### Function 41: "\*NDArray\*.tolist()"

This Function converts an NDArray to a Python List.

In [47]:
pythonList = myArray.tolist()
print(pythonList)

[[4.64705064110167e-310, 0.0, 6.91501177463387e-310, 6.91501177463703e-310, 6.9150117746402e-310], [6.91501177464336e-310, 6.9150117746465e-310, 6.9150117746497e-310, 6.91501177465284e-310, 6.915011774656e-310], [6.91501177465917e-310, 6.91501177466233e-310, 6.9150117746655e-310, 6.91501177466865e-310, 6.9150117746718e-310], [6.915011774675e-310, 6.91501177467814e-310, 6.9150117746813e-310, 6.91501177468446e-310, 6.9150117746876e-310], [6.9150117746908e-310, 6.91501177469395e-310, 6.9150117746971e-310, 6.91501177470027e-310, 1.03e-321]]


##### Function 42: "\*NDArray*\.astype()"

This Function converts NDArray Elements to the Data Type specified.

In [48]:
myArray.astype(str)

array([['4.64705064110167e-310', '0.0', '6.91501177463387e-310',
        '6.91501177463703e-310', '6.9150117746402e-310'],
       ['6.91501177464336e-310', '6.9150117746465e-310',
        '6.9150117746497e-310', '6.91501177465284e-310',
        '6.915011774656e-310'],
       ['6.91501177465917e-310', '6.91501177466233e-310',
        '6.9150117746655e-310', '6.91501177466865e-310',
        '6.9150117746718e-310'],
       ['6.915011774675e-310', '6.91501177467814e-310',
        '6.9150117746813e-310', '6.91501177468446e-310',
        '6.9150117746876e-310'],
       ['6.9150117746908e-310', '6.91501177469395e-310',
        '6.9150117746971e-310', '6.91501177470027e-310', '1.03e-321']],
      dtype='<U32')

##### Function 43: "\*NDArray*\.info()"

This Function outputs the Documentation for the NumPy Function specified.

In [49]:
numpy.info(numpy.ndarray)

 ndarray()

ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer interface, optional
    Used to fill the array with data.
of

##### Function 44: "\*NDArray\*.resize()"

This Function resizes the NDArray specified to a any Dimension specified and fills the new Elements/Values with 0's (it doesn't actually assign 0's to the values as they are Empty, 0's is just a way to represent the Empty Elements/Values and this is why when you try to print the NDArray, it outputs None instead of a bunch of 0's).

In [50]:
newDecimalArray = decimalArray.resize((1, 10))
print(newDecimalArray)

None


##### Function 45: "numpy.append()"

This Function Appends Elements to the end of the NDArray specified.

In [51]:
numpy.append(array, [3, 2, 7, 9, 6])

array([  5,   9,  -2,  -5,  14,  18, -25, -53,   3,   2,   7,   9,   6])

##### Function 46: "numpy.insert()"

This Function Inserts Elements after the Index of the NDArray specified.

In [52]:
numpy.insert(array, 2, [1, 2, 3, 4, 5])

array([  5,   9,   1,   2,   3,   4,   5,  -2,  -5,  14,  18, -25, -53])

##### Function 47: "numpy.delete()"

This Function deletes a Row/Column on the Axis and Index of the NDArray specified.

In [53]:
numpy.delete(myArray, 2, 0)

array([[4.64705064e-310, 0.00000000e+000, 6.91501177e-310,
        6.91501177e-310, 6.91501177e-310],
       [6.91501177e-310, 6.91501177e-310, 6.91501177e-310,
        6.91501177e-310, 6.91501177e-310],
       [6.91501177e-310, 6.91501177e-310, 6.91501177e-310,
        6.91501177e-310, 6.91501177e-310],
       [6.91501177e-310, 6.91501177e-310, 6.91501177e-310,
        6.91501177e-310, 1.02765654e-321]])

##### Function 48: "numpy.where()"

This Function returns Elements from an NDArray that match the given Condition.

In [54]:
numpy.where(array > 0)

(array([0, 1, 4, 5]),)

##### Function 49: "numpy.round()"

This Function Rounds an NDArray to the given number of Decimals.

In [55]:
numpy.round([72.789, 9.245, 83.7, 63.276, 98.2, 63.67576])

array([73.,  9., 84., 63., 98., 64.])

##### Function 50: "numpy.count_nonzero()"

This Function counts the number of Non-Zero Values in the NDArray specified.

In [56]:
numpy.count_nonzero([0, 7, 5, 2, 0, 9, 0, 4, 6, 0])

6